#!/usr/bin/perl
# gen-unicode.pl - generate src/unitab.c, the Unicode tables the tokenizer's
# pre-tokenizer needs (letters, numbers, white space), from Perl's own Unicode
# database. Run: perl tools/gen-unicode.pl > src/unitab.c
use strict;
use warnings;
use Unicode::UCD qw(prop_invlist);

print "/* unitab.c - generated by tools/gen-unicode.pl; do not edit.\n";
print " * Unicode version " . Unicode::UCD::UnicodeVersion() . ". Each table is an inversion list:\n";
print " * sorted code points where membership toggles, starting with \"in\". */\n";
print "#include \"unitab.h\"\n\n";
my %sets = (letter => 'L', number => 'N', space => 'White_Space');
for my $name (sort keys %sets) {
    my @inv = prop_invlist($sets{$name});
    print "const uint32_t hfc_uni_${name}[] = {";
    for my $i (0 .. $#inv) { print "\n    " if $i % 8 == 0; printf "0x%x,", $inv[$i]; print " " if $i % 8 != 7 && $i != $#inv; }
    print "\n};\nconst size_t hfc_uni_${name}_n = ", scalar(@inv), ";\n\n";
}
